modLoader="javafml" #mandatory
loaderVersion="[30,)"

issueTrackerURL="https://github.com/WTBW-Mods/WTBW_Lib/issues/"

[[mods]]
modId="wtbw_lib"
version="${file.jarVersion}"
displayName="WTBW Library"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="tools.png"
authors="Naxanria, Sunekaer" #optional
description='''
Library mod
'''
[[dependencies.wtbw_lib]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_lib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
